Repository bardhprenkaj/ML_labs, pull requests merged in 2023-12, with the labels that each got.

#2 vidig47.ipynb solution to lab 1
  src/2023_22/lab1/solutions/vidig47.ipynb
Labels: enhancement

#4 Add files via upload
  src/2023_22/lab1/solutions/Bruzzese-953247-Exercise_Fine_Tuning_XGBoost_on_Heart_Disease_Prediction-2.ipynb
Labels: enhancement

#6 Update README.md
  README.md
Labels: documentation

#7 Dodo.ipynb solution to lab 1 (updated)
  src/2023_22/lab1/solutions/Dodo.ipynb
Labels: enhancement

#8 Elia Di Santo solution ex 1
  src/2023_22/lab1/solutions/Elia Di Santo solution ex 1
Labels: duplicate, enhancement

#13 added my solution
  src/2023_22/lab1/solutions/bellantone1_ipynbb.ipynb
Labels: enhancement

#12 frascarelli's solution
  src/2023_22/lab1/solutions/frascarelli_sol1.ipynb
Labels: enhancement

#9 Adding my solution to lab 1
  src/2023_22/lab1/solutions/solaire_of_astora.ipynb
Labels: enhancement

#16 Angel Sanchez solution
  src/2023_22/lab1/solutions/angeloyo_lab1.ipynb
Labels: enhancement

#18 Completed first homework
  src/2023_22/lab1/solutions/brasilnike.ipynb
Labels: enhancement

#19 Solution 1 Hannes Pohnke
  src/2023_22/lab1/solutions/fref_sol1.ipynb
Labels: enhancement

#21 CHiara Frascaria lab1 solutions
  src/2023_22/lab1/solutions/FrascariaChiara_Exercise_Fine_Tuning_XGBoost_on_Heart_Disease_Prediction.ipynb
Labels: enhancement

#26 Solution1_Lundholm
  src/2023_22/lab1/solutions/Solution1_lundholm.ipynb
Labels: enhancement

#27 Solution Wodo lab1
  src/2023_22/lab1/solutions/wodo.ipynb
Labels: enhancement

#28 Solutions Lab1 Mariolino
  src/2023_22/lab1/solutions/mariolino_lab1.ipynb
Labels: enhancement

#29 Solution Daniel FU
  src/2023_22/lab1/solutions/DanielFU.ipynb
Labels: enhancement

#30 Upload lab1 renella
  src/2023_22/lab1/solutions/renella.ipynb
Labels: enhancement

#31 Add files via upload
  src/2023_22/lab1/solutions/mart8la_lab1.ipynb
Labels: enhancement

#32 Added solution of first lab
  src/2023_22/lab1/solutions/fasble.ipynb
Labels: enhancement

#51 Added Solution to lab3 folder
  src/2023/lab3/submissions/Wodo.ipynb
Labels: enhancement

#50 Add Angel Sanchez Lab3 solution
  src/2023/lab3/submissions/lab3_hw_AngelSanchezGuerrero.ipynb
Labels: enhancement

#46 fref solution lab3
  src/2023/lab3/submissions/fref_sol2.ipynb
Labels: enhancement
